import { CampaignTable } from "@/components/dashboard/CampaignTable";
import type { ReportHighlights } from "@/app/api/generate-report/route";

const kpis = [
  { label: "Total spend", value: "RM 12,480" },
  { label: "Total leads", value: "348" },
  { label: "Blended ROAS", value: "4.2×" },
  { label: "Avg CPL", value: "RM 35.9" },
];

type ReportDocumentProps = {
  period: string;
  summary: string;
  highlights: ReportHighlights;
  recommendations: string[];
  isStreaming?: boolean;
};

export function ReportDocument({
  period,
  summary,
  highlights,
  recommendations,
  isStreaming = false,
}: ReportDocumentProps) {
  return (
    <div className="overflow-hidden rounded-xl border border-border bg-surface shadow-sm">
      <div className="bg-[#111827] px-6 py-6 text-white dark:bg-[#0B0D12]">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex items-start gap-3">
            <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-orange text-sm font-semibold text-white">
              A
            </span>
            <div>
              <p className="text-[14px] font-semibold">AM Interpretiv</p>
              <p className="mt-0.5 text-[12px] text-white/70">
                Performance Report · {period}
              </p>
            </div>
          </div>
          <span className="inline-flex w-fit rounded-md border border-white/15 bg-white/10 px-2.5 py-1 text-[11px] font-medium text-white/90">
            Generated by ASHI
          </span>
        </div>

        <h1 className="mt-6 text-[28px] font-semibold tracking-tight">
          June Performance Report
        </h1>

        <div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
          {kpis.map((kpi) => (
            <div
              key={kpi.label}
              className="rounded-lg border border-white/10 bg-white/5 px-4 py-3"
            >
              <p className="text-[11px] font-medium uppercase tracking-wide text-white/60">
                {kpi.label}
              </p>
              <p className="mt-1 text-[20px] font-semibold">{kpi.value}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-8 px-6 py-8">
        <section>
          <div className="flex items-center gap-2">
            <h2 className="text-[15px] font-semibold text-text">ASHI Summary</h2>
            {isStreaming && (
              <span className="inline-flex rounded-md bg-orange-pale px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-orange">
                Writing
              </span>
            )}
          </div>
          <p className="mt-3 text-[13px] leading-relaxed text-text-2">
            {summary}
            {isStreaming && (
              <span className="ml-0.5 inline-block h-4 w-0.5 animate-pulse bg-orange align-middle" />
            )}
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-[15px] font-semibold text-text">
            Highlights
          </h2>
          <div className="grid gap-4 lg:grid-cols-3">
            <div className="rounded-xl border border-green/20 bg-green-pale p-4">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-green-text">
                Win
              </p>
              <p className="mt-2 text-[13px] leading-relaxed text-text-2">
                {highlights.win}
              </p>
            </div>
            <div className="rounded-xl border border-red/20 bg-red-pale p-4">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-red-text">
                Watch
              </p>
              <p className="mt-2 text-[13px] leading-relaxed text-text-2">
                {highlights.watch}
              </p>
            </div>
            <div className="rounded-xl border border-orange-border bg-orange-pale p-4">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-orange">
                Next steps
              </p>
              <p className="mt-2 text-[13px] leading-relaxed text-text-2">
                {highlights.nextSteps}
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="mb-3 text-[15px] font-semibold text-text">
            Campaign performance
          </h2>
          <CampaignTable embedded />
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text">
            Recommendations
          </h2>
          <ol className="mt-4 space-y-3">
            {recommendations.map((item, index) => (
              <li key={`${index}-${item.slice(0, 24)}`} className="flex gap-3 text-[13px] leading-relaxed">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-orange-pale text-[11px] font-semibold text-orange">
                  {index + 1}
                </span>
                <span className="pt-0.5 text-text-2">{item}</span>
              </li>
            ))}
          </ol>
        </section>
      </div>
    </div>
  );
}
